name: Notify Parent Repo

on:
  push:
    branches:
      - main

jobs:
  ping-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Parent Update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MAIN_REPO_UPDATE_TOKEN }}
          repository: GameoCoder/HQML-Platform
          event-type: submodule_updated
